# Generated by Django 4.1.7 on 2023-03-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stuname',
        ),
        migrations.AddField(
            model_name='student',
            name='cal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
