# Generated by Django 4.1.7 on 2023-03-28 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_student_cal_student_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='stuname',
        ),
    ]
