# Generated by Django 4.1.7 on 2023-04-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_student_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='cal',
            field=models.IntegerField(),
        ),
    ]
