# Generated by Django 4.1.7 on 2023-04-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_food_cal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='cal',
            field=models.CharField(max_length=100),
        ),
    ]
