# Generated by Django 4.1.7 on 2023-04-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_food_cal'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodaysCalories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cal', models.IntegerField()),
            ],
        ),
    ]
