# Generated by Django 4.1.7 on 2023-04-08 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_todayscalories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todayscalories',
            name='cal',
        ),
        migrations.RemoveField(
            model_name='todayscalories',
            name='name',
        ),
        migrations.AddField(
            model_name='todayscalories',
            name='fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.food'),
            preserve_default=False,
        ),
    ]
