# Generated by Django 4.1.7 on 2023-04-08 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_todayscalories_cal_remove_todayscalories_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodaysCalories',
            new_name='Today',
        ),
    ]
