# Generated by Django 4.1.7 on 2023-04-11 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_today_fk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Today',
        ),
    ]
