# Generated by Django 4.1.7 on 2023-04-11 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_delete_today'),
    ]

    operations = [
        migrations.CreateModel(
            name='Today',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk', models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='api.food')),
            ],
        ),
    ]
